version: "3.9"

services:
  app:
    container_name: app
    build: 
      context: app
      args: 
        PORT: 3000
        SQLITE_LOCATION: /etc/todos/todo.db
    ports: 
      - 3000:3000
    # volumes:
    #   - todos:/etc/todos
    depends_on: 
      - backend
    networks: 
      - public

  backend:
    build: 
      args:
        NODE_ENV: production
    environment:
      DATABASE_DB: example
      DATABASE_USER: root
      DATABASE_PASSWORD: /run/secrets/db-password
      DATABASE_HOST: db
      NODE_ENV: production
    ports: 
      - 80:80
      - 9229:9229
      - 9230:9230
    depends_on: 
      - db
    networks: 
      - private
      - public
    secrets:
      - db-password

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=/run/secrets/db-password
    secrets:
      - db-password
    networks: 
      - private

secrets:
  db-password:
    file: ./db-password.txt

volumes: 
  # todos:
  db-data:

networks: 
  private:
  public:
